app:
  request-host: apitest.cybersource.com
  merchant-id: alone_tmid001
  merchant-key-id: 6c56f759-9bdd-443e-8361-a4bc3f5701ce
  merchant-secret-key: iln9YDngM+HrD9UKguV/PmDckrcbaOzdCh96dVVJCe4=

cybersource:
  merchant-id: alone_tmid001
  run-environment: apitest.cybersource.com
  authentication-type: http_signature
  merchant-key-id: 6c56f759-9bdd-443e-8361-a4bc3f5701ce
  merchant-secret-key: iln9YDngM+HrD9UKguV/PmDckrcbaOzdCh96dVVJCe4=

server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
    key-alias: myalias

spring:
  thymeleaf:
    cache: false
